name: docker-deploy

on:
  push:
    branches: [ main ]

jobs:     
  DOCKER_BUILD_AND_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
        
      - name: build docker image
        run: docker build -t migsking/hello-world .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: migsking/hello-world
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
